CREATE TABLE role (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    firstname VARCHAR(50),
    lastname VARCHAR(50),
    password VARCHAR(50) NOT NULL,
    roleId INTEGER NOT NULL,
    classId INTEGER,
    email VARCHAR(50),
    FOREIGN KEY (roleId) REFERENCES role(id),
    FOREIGN KEY (classId) REFERENCES class(id)
);

CREATE TABLE class (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name VARCHAR(50) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS user;